<?php

use Drupal\block\Entity\Block;

/*
*function hook_theme()
*/

function accenture_common_theme($existing, $type, $theme, $path) {
  return [
    'faq-block' => [
      'variables' => ['faqs' => NULL,'faqsDetails' => NULL],
    ],
    'slider-block' => [
      'variables' => ['homeslider' => NULL],
    ],
    'middle-slider-block' => [
      'variables' => ['network' => NULL],
    ],
    'feature-block' => [
      'variables' => ['feature' => NULL],
    ],
  ];
}

function accenture_common_preprocess_node(&$variables){

  $data = \Drupal::service('accenture_common.custom_services')->getData();
  var_dump($data);
}